on:
  push:

name: linting

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install tf-docs
        run: GO111MODULE="on" go get github.com/terraform-docs/terraform-docs@v0.10.1
      - uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
